source "https://rubygems.org"
gem "asciidoctor-pdf",
  git: "https://github.com/magentastripe/asciidoctor-pdf",
  branch: "2.3.9-magentastripe"
gem "asciidoctor-epub3",
  git: "https://github.com/magentastripe/asciidoctor-epub3",
  branch: "magentastripe"
gem "epubcheck-ruby"
gem "rghost"
