source "https://rubygems.org"
gem "asciidoctor-pdf", git: "https://github.com/dressupgeekout/asciidoctor-pdf", branch: "2.3.9-charlotte"
gem "asciidoctor-epub3", git: "https://github.com/dressupgeekout/asciidoctor-epub3", branch: "charlotte"
gem "epubcheck-ruby"
gem "rghost"
